version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file: .env # Load variables from .env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: